name: Merge Develop

on:
  push:
    branches: [develop]

jobs:
  build_binary:
    name: Build docker image and tag to dev
    environment:
      name: dev
      url: https://hub.dev.immutable.com
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Set env vars
        run: |
          echo BUILD_TIMESTAMP="$(date +%s)" >> $GITHUB_ENV
          echo REPOSITORY_NAME="$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
          echo TAG_NAME="$(echo ${{ github.ref }} | cut -d / -f3-)" >> $GITHUB_ENV
          echo SHORT_SHA="$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo LATEST_VERSION="$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo BRANCH="$(git rev-parse --abbrev-ref HEAD | tr -d '\040\011\012\015\n')" >> $GITHUB_ENV
          echo TIME="$(date)" >> $GITHUB_ENV
      - name: Build
        env:
          CC: gcc
          CXX: g++
          GOARC: amd64
          GOOS: linux
        run: go build -ldflags='-s -w -linkmode external -extldflags "-static"' -o polygon-edge -ldflags="\
            -X 'github.com/0xPolygon/polygon-edge/versioning.Version=${{ env.LATEST_VERSION }}' \
            -X 'github.com/0xPolygon/polygon-edge/versioning.Commit=${{ env.SHORT_SHA }}'\
            -X 'github.com/0xPolygon/polygon-edge/versioning.Branch=${{ env.BRANCH }}'\
            -X 'github.com/0xPolygon/polygon-edge/versioning.BuildTime=${{ env.TIME }}'" \
            main.go
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: polygon-edge
          path: ./polygon-edge
